<a href="https://colab.research.google.com/github/sangramshitole07/PythonCourse/blob/main/Python_Course_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

#creating a Array using numpy
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
#reshape array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [21]:
#or we can also declare it as 2d
arr2=np.array([[1,2,3,4,5]])
print(arr2)
print(type(arr2))
print(arr2.shape)
#properties of np/array
print(np.shape(arr2))
print(np.ndim(arr2))
print(np.size(arr2))
#functions that operate on object
type(arr2)
len(arr)
np.sum(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)


[[1 2 3 4 5]]
<class 'numpy.ndarray'>
(1, 5)
(1, 5)
2
5


np.int64(5)

In [12]:
arr3=[[1,2,3],[4,5,6]]
print(type(arr3))

<class 'list'>


In [42]:
one=np.ones((3,3))
print(one)
print(one.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
8


In [43]:
## Nump