<a href="https://colab.research.google.com/github/sangramshitole07/PythonCourse/blob/main/Python_Course_Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import numpy as np

#creating a Array using numpy
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
#reshape array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5)

In [ ]:
#or we can also declare it as 2d
arr2=np.array([[1,2,3,4,5]])
print(arr2)
print(type(arr2))
print(arr2.shape)
#properties of np/array
print(np.shape(arr2))
print(np.ndim(arr2))
print(np.size(arr2))
#functions that operate on object
type(arr2)
len(arr)
np.sum(arr)
np.mean(arr)
np.median(arr)
np.std(arr)
np.var(arr)
np.min(arr)
np.max(arr)


In [ ]:
arr3=[[1,2,3],[4,5,6]]
print(type(arr3))

In [ ]:
one=np.ones((3,3))
print(one)
print(one.itemsize)

In [ ]:
#rearrange the shape

In [27]:
# numpy vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
#element addition, subtration , multiplication and division

print("Addition :", arr1+arr2)
print("Subtration:", arr1-arr2)
print("Multiplication: ", arr1*arr2)
print("Division: ", arr1//arr2)
print(10/3)
print(10//3)

Addition : [ 7  9 11 13 15]
Subtration: [-5 -5 -5 -5 -5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0 0 0 0 0]
3.3333333333333335
3


In [25]:
import numpy
import importlib
importlib.reload(numpy)
import numpy as np
#universal function
arr=np.array([1,4,9,16,25])
print(" square root",np.sqrt(arr))
print("Log :",np.log(arr))
print("exp :",np.exp(arr))
print("Sin function",np.sin(arr))
print("Cos function",np.cos(arr))
print("Tan fun :",np.tan(arr))

 square root [1. 2. 3. 4. 5.]
Log : [0.         1.38629436 2.19722458 2.77258872 3.21887582]
exp : [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
Sin function [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
Cos function [ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]
Tan fun : [ 1.55740772  1.15782128 -0.45231566  0.30063224 -0.13352641]


/usr/lib/python3.12/importlib/__init__.py:131: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  _bootstrap._exec(spec, module)


In [29]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [30]:
print(arr[0,0])

1


In [36]:
print(arr[0:1,0:3])

[[1 2 3]]


In [37]:
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [39]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
data =np.array([1,2,3,4,5,6])
mean=np.mean(data)
print("menan :",mean)
std=np.std(data)
print("std :",std)
normalize=(data-mean/std)
print("normalize :",normalize)
median=np.median(data)
print("median :",median)
varience=np.var(data)
print("varience :",varience)



menan : 3.5
std : 1.707825127659933
normalize : [-1.04939015 -0.04939015  0.95060985  1.95060985  2.95060985  3.95060985]
median : 3.5
varience : 2.9166666666666665
